language: python
python:
  - 3.8
  - 3.7
  - 3.6
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/user_mixins'
  matrix:
    - DJANGO='django~=3.1.0'
    - DJANGO='django~=3.0.0'
    - DJANGO='django~=2.2.0'
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'CREATE DATABASE user_mixins' -U postgres;
install:
  - pip install -r requirements.txt
  - pip install --upgrade $DJANGO
